name: Test Package
on: [push]

jobs:
  test:
    strategy:
      matrix:
        package: [alpha, omega]
        # Run tests with all of these node versions/systems :]
        node-version: [10.x]
        # os: [ubuntu-latest, windows-latest, macOS-latest]
        os: [ubuntu-latest]
    name: ${{ matrix.package }} with Node ${{ matrix.node-version }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node_modules
        id: cache_node_modules
        uses: actions/cache@master
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
      - run: yarn lerna bootstrap

      - name: Coverage ${{ matrix.package }}
        run: cd packages/${{ matrix.package }} && yarn test --coverage
        env:
          CI: true
      - run: echo $PKG_FLAG
        env:
          PKG_FLAG: $(echo ${{ matrix.package }} | perl -pe 's/(^|-)./uc($&)/ge;s/-//g')
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./packages/${{ matrix.package }}/coverage/clover.xml
          flags: $PKG_FLAG
          fail_ci_if_error: true
        env:
          PKG_FLAG: $(echo ${{ matrix.package }} | perl -pe 's/(^|-)./uc($&)/ge;s/-//g')
